export const mockVisaSaoudit = [
  {
    id: 1,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Marocaine',
    firstNameEn: 'Mohamed',
    fatherNameEn: 'El Hassan',
    lastNameEn: 'El Bekkali',
    gender: 'Male',
    maritalStatus: 'Married',
    dateOfBirth: '1998-05-12',
    countryOfBirth: 'Maroc',
    cityOfBirth: 'Fès',
    profession: 'Développeur Full Stack',
    countryResidence: 'France',
    cityResidence: 'Lyon',
    postalCode: '69008',
    address: '12 Rue de Marseille, Lyon',
    passportType: 'Ordinary',
    passportNumber: 'XA452789',
    passportIssuePlace: 'Fès',
    passportIssueDate: '2020-03-10',
    passportExpiryDate: '2030-03-10',
    expectedDateEntry: '2025-04-10',
    expectedDateLeave: '2025-04-25',
    additionalPurpose: ['Tourisme', 'Famille'],
    residenceAddressSaudi: 'Riyadh Central District',
    hotelName: 'Hilton Riyadh',
  },
  {
    id: 2,
    personal_picture: '/images/sara.jpg',
    nationality: 'Algérienne',
    firstNameEn: 'Sara',
    fatherNameEn: 'Abderrahmane',
    lastNameEn: 'Mansouri',
    gender: 'Female',
    maritalStatus: 'Single',
    dateOfBirth: '1995-09-22',
    countryOfBirth: 'Algérie',
    cityOfBirth: 'Oran',
    profession: 'Infirmière',
    countryResidence: 'France',
    cityResidence: 'Marseille',
    postalCode: '13008',
    address: '45 Avenue du Prado, Marseille',
    passportType: 'Ordinary',
    passportNumber: 'DZ998321',
    passportIssuePlace: 'Oran',
    passportIssueDate: '2019-07-15',
    passportExpiryDate: '2029-07-15',
    expectedDateEntry: '2025-05-03',
    expectedDateLeave: '2025-05-13',
    additionalPurpose: ['Omra'],
    residenceAddressSaudi: 'Makkah Haram Zone',
    hotelName: 'Swissotel Al Maqam',
  },

  // ✅ 3 → 20 : données générées

  {
    id: 3,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Tunisienne',
    firstNameEn: 'Ahmed',
    fatherNameEn: 'Sofiane',
    lastNameEn: 'Ben Salem',
    gender: 'Male',
    maritalStatus: 'Single',
    dateOfBirth: '1992-01-14',
    countryOfBirth: 'Tunisie',
    cityOfBirth: 'Tunis',
    profession: 'Ingénieur Réseau',
    countryResidence: 'France',
    cityResidence: 'Nice',
    postalCode: '06000',
    address: '8 Rue Masséna, Nice',
    passportType: 'Ordinary',
    passportNumber: 'TN442199',
    passportIssuePlace: 'Tunis',
    passportIssueDate: '2018-05-12',
    passportExpiryDate: '2028-05-12',
    expectedDateEntry: '2025-04-18',
    expectedDateLeave: '2025-04-30',
    additionalPurpose: ['Omra'],
    residenceAddressSaudi: 'Medina North District',
    hotelName: 'Pullman ZamZam Madinah',
  },
  {
    id: 4,
    personal_picture: '/images/sara.jpg',
    nationality: 'Marocaine',
    firstNameEn: 'Fatima',
    fatherNameEn: 'Jamal',
    lastNameEn: 'El Yousfi',
    gender: 'Female',
    maritalStatus: 'Married',
    dateOfBirth: '1993-11-02',
    countryOfBirth: 'Maroc',
    cityOfBirth: 'Rabat',
    profession: 'Enseignante',
    countryResidence: 'Belgique',
    cityResidence: 'Bruxelles',
    postalCode: '1000',
    address: '21 Avenue Louise, Bruxelles',
    passportType: 'Ordinary',
    passportNumber: 'MA882341',
    passportIssuePlace: 'Rabat',
    passportIssueDate: '2017-09-18',
    passportExpiryDate: '2027-09-18',
    expectedDateEntry: '2025-06-04',
    expectedDateLeave: '2025-06-15',
    additionalPurpose: ['Tourisme'],
    residenceAddressSaudi: 'Jeddah Corniche',
    hotelName: 'InterContinental Jeddah',
  },
  {
    id: 5,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Egyptienne',
    firstNameEn: 'Youssef',
    fatherNameEn: 'Karim',
    lastNameEn: 'Mahmoud',
    gender: 'Male',
    maritalStatus: 'Married',
    dateOfBirth: '1988-03-09',
    countryOfBirth: 'Égypte',
    cityOfBirth: 'Le Caire',
    profession: 'Comptable',
    countryResidence: 'France',
    cityResidence: 'Toulouse',
    postalCode: '31000',
    address: '67 Rue Alsace Lorraine, Toulouse',
    passportType: 'Ordinary',
    passportNumber: 'EG293811',
    passportIssuePlace: 'Cairo',
    passportIssueDate: '2021-04-10',
    passportExpiryDate: '2031-04-10',
    expectedDateEntry: '2025-07-12',
    expectedDateLeave: '2025-07-22',
    additionalPurpose: ['Famille'],
    residenceAddressSaudi: 'Riyadh Exit 7',
    hotelName: 'Hyatt Regency Riyadh',
  },
  {
    id: 6,
    personal_picture: '/images/sara.jpg',
    nationality: 'Tunisienne',
    firstNameEn: 'Kawthar',
    fatherNameEn: 'Hedi',
    lastNameEn: 'Ben Jrad',
    gender: 'Female',
    maritalStatus: 'Widow',
    dateOfBirth: '1987-07-19',
    countryOfBirth: 'Tunisie',
    cityOfBirth: 'Sousse',
    profession: 'Pharmacienne',
    countryResidence: 'France',
    cityResidence: 'Paris',
    postalCode: '75015',
    address: '33 Rue de Vaugirard, Paris',
    passportType: 'Ordinary',
    passportNumber: 'TN884321',
    passportIssuePlace: 'Sousse',
    passportIssueDate: '2020-02-11',
    passportExpiryDate: '2030-02-11',
    expectedDateEntry: '2025-08-03',
    expectedDateLeave: '2025-08-19',
    additionalPurpose: ['Omra'],
    residenceAddressSaudi: 'Makkah Haram',
    hotelName: 'Hilton Suites Makkah',
  },
  {
    id: 7,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Libyenne',
    firstNameEn: 'Omar',
    fatherNameEn: 'Saleh',
    lastNameEn: 'Al Mansouri',
    gender: 'Male',
    maritalStatus: 'Single',
    dateOfBirth: '1990-12-01',
    countryOfBirth: 'Libye',
    cityOfBirth: 'Tripoli',
    profession: 'Médecin',
    countryResidence: 'France',
    cityResidence: 'Lille',
    postalCode: '59000',
    address: '14 Rue Nationale, Lille',
    passportType: 'Ordinary',
    passportNumber: 'LY522100',
    passportIssuePlace: 'Tripoli',
    passportIssueDate: '2016-08-21',
    passportExpiryDate: '2026-08-21',
    expectedDateEntry: '2025-05-11',
    expectedDateLeave: '2025-05-21',
    additionalPurpose: ['Conférence'],
    residenceAddressSaudi: 'Riyadh Diplomatic Quarter',
    hotelName: 'Ritz Carlton Riyadh',
  },
  {
    id: 8,
    personal_picture: '/images/sara.jpg',
    nationality: 'Marocaine',
    firstNameEn: 'Imane',
    fatherNameEn: 'Amine',
    lastNameEn: 'Berrada',
    gender: 'Female',
    maritalStatus: 'Divorced',
    dateOfBirth: '1994-04-27',
    countryOfBirth: 'Maroc',
    cityOfBirth: 'Casablanca',
    profession: 'Designer UX/UI',
    countryResidence: 'France',
    cityResidence: 'Lyon',
    postalCode: '69003',
    address: '90 Rue Paul Bert, Lyon',
    passportType: 'Ordinary',
    passportNumber: 'MA441199',
    passportIssuePlace: 'Casa',
    passportIssueDate: '2021-01-02',
    passportExpiryDate: '2031-01-02',
    expectedDateEntry: '2025-09-02',
    expectedDateLeave: '2025-09-14',
    additionalPurpose: ['Tourisme'],
    residenceAddressSaudi: 'Riyadh Olaya Street',
    hotelName: 'Narcissus Hotel Riyadh',
  },

  {
    id: 9,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Algérienne',
    firstNameEn: 'Nassim',
    fatherNameEn: 'Farid',
    lastNameEn: 'Boukercha',
    gender: 'Male',
    maritalStatus: 'Single',
    dateOfBirth: '1996-02-11',
    countryOfBirth: 'Algérie',
    cityOfBirth: 'Blida',
    profession: 'Technicien IT',
    countryResidence: 'France',
    cityResidence: 'Rouen',
    postalCode: '76000',
    address: '58 Rue Jeanne d’Arc, Rouen',
    passportType: 'Ordinary',
    passportNumber: 'DZ332110',
    passportIssuePlace: 'Blida',
    passportIssueDate: '2019-12-20',
    passportExpiryDate: '2029-12-20',
    expectedDateEntry: '2025-10-05',
    expectedDateLeave: '2025-10-16',
    additionalPurpose: ['Omra'],
    residenceAddressSaudi: 'Medina South District',
    hotelName: 'Madinah Hilton',
  },

  {
    id: 10,
    personal_picture: '/images/sara.jpg',
    nationality: 'Egyptienne',
    firstNameEn: 'Mona',
    fatherNameEn: 'Yasser',
    lastNameEn: 'Hassan',
    gender: 'Female',
    maritalStatus: 'Married',
    dateOfBirth: '1989-10-14',
    countryOfBirth: 'Égypte',
    cityOfBirth: 'Alexandria',
    profession: 'Professeur Universitaire',
    countryResidence: 'France',
    cityResidence: 'Grenoble',
    postalCode: '38000',
    address: '15 Rue Lesdiguières, Grenoble',
    passportType: 'Ordinary',
    passportNumber: 'EG712990',
    passportIssuePlace: 'Alexandria',
    passportIssueDate: '2020-06-11',
    passportExpiryDate: '2030-06-11',
    expectedDateEntry: '2025-03-28',
    expectedDateLeave: '2025-04-08',
    additionalPurpose: ['Recherche'],
    residenceAddressSaudi: 'Jeddah King Road',
    hotelName: 'Radisson Blu Jeddah',
  },

  // ✅ Continue jusqu’à 20

  {
    id: 11,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Marocaine',
    firstNameEn: 'Anas',
    fatherNameEn: 'Hamid',
    lastNameEn: 'Rahhali',
    gender: 'Male',
    maritalStatus: 'Single',
    dateOfBirth: '1997-06-07',
    countryOfBirth: 'Maroc',
    cityOfBirth: 'Tanger',
    profession: 'Consultant',
    countryResidence: 'France',
    cityResidence: 'Bordeaux',
    postalCode: '33000',
    address: '20 Cours Victor Hugo, Bordeaux',
    passportType: 'Ordinary',
    passportNumber: 'MA991200',
    passportIssuePlace: 'Tanger',
    passportIssueDate: '2021-03-09',
    passportExpiryDate: '2031-03-09',
    expectedDateEntry: '2025-11-10',
    expectedDateLeave: '2025-11-22',
    additionalPurpose: ['Famille'],
    residenceAddressSaudi: 'Riyadh Hittin District',
    hotelName: 'Holiday Inn Riyadh',
  },

  {
    id: 12,
    personal_picture: '/images/sara.jpg',
    nationality: 'Algérienne',
    firstNameEn: 'Nadia',
    fatherNameEn: 'Samir',
    lastNameEn: 'Bouhired',
    gender: 'Female',
    maritalStatus: 'Divorced',
    dateOfBirth: '1991-02-21',
    countryOfBirth: 'Algérie',
    cityOfBirth: 'Tizi Ouzou',
    profession: 'Architecte',
    countryResidence: 'France',
    cityResidence: 'Strasbourg',
    postalCode: '67000',
    address: '89 Rue des Grandes Arcades',
    passportType: 'Ordinary',
    passportNumber: 'DZ990123',
    passportIssuePlace: 'Tizi Ouzou',
    passportIssueDate: '2022-01-12',
    passportExpiryDate: '2032-01-12',
    expectedDateEntry: '2025-12-05',
    expectedDateLeave: '2025-12-17',
    additionalPurpose: ['Tourisme'],
    residenceAddressSaudi: 'Jeddah Al Balad',
    hotelName: 'Ramada by Wyndham Jeddah',
  },

  {
    id: 13,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Egyptienne',
    firstNameEn: 'Karim',
    fatherNameEn: 'Mahmoud',
    lastNameEn: 'Osman',
    gender: 'Male',
    maritalStatus: 'Married',
    dateOfBirth: '1984-07-30',
    countryOfBirth: 'Égypte',
    cityOfBirth: 'Giza',
    profession: 'Chef de projet IT',
    countryResidence: 'France',
    cityResidence: 'Roubaix',
    postalCode: '59100',
    address: '59 Boulevard Gambetta',
    passportType: 'Ordinary',
    passportNumber: 'EG711231',
    passportIssuePlace: 'Giza',
    passportIssueDate: '2019-09-01',
    passportExpiryDate: '2029-09-01',
    expectedDateEntry: '2025-09-14',
    expectedDateLeave: '2025-09-26',
    additionalPurpose: ['Affaires'],
    residenceAddressSaudi: 'Riyadh King Fahd Road',
    hotelName: 'Courtyard by Marriott Riyadh',
  },

  {
    id: 14,
    personal_picture: '/images/sara.jpg',
    nationality: 'Tunisienne',
    firstNameEn: 'Sana',
    fatherNameEn: 'Mourad',
    lastNameEn: 'Ben Ali',
    gender: 'Female',
    maritalStatus: 'Single',
    dateOfBirth: '1998-08-19',
    countryOfBirth: 'Tunisie',
    cityOfBirth: 'Monastir',
    profession: 'Styliste',
    countryResidence: 'France',
    cityResidence: 'Nantes',
    postalCode: '44000',
    address: '13 Quai de la Fosse',
    passportType: 'Ordinary',
    passportNumber: 'TN551234',
    passportIssuePlace: 'Monastir',
    passportIssueDate: '2020-11-05',
    passportExpiryDate: '2030-11-05',
    expectedDateEntry: '2025-03-04',
    expectedDateLeave: '2025-03-15',
    additionalPurpose: ['Tourisme'],
    residenceAddressSaudi: 'Medina Haram West',
    hotelName: 'Dar Al Eiman Grand',
  },

  {
    id: 15,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Marocaine',
    firstNameEn: 'Zakaria',
    fatherNameEn: 'Mostafa',
    lastNameEn: 'Haddadi',
    gender: 'Male',
    maritalStatus: 'Married',
    dateOfBirth: '1993-09-05',
    countryOfBirth: 'Maroc',
    cityOfBirth: 'Marrakech',
    profession: 'Agent Commercial',
    countryResidence: 'France',
    cityResidence: 'Toulouse',
    postalCode: '31500',
    address: '18 Rue de Metz',
    passportType: 'Ordinary',
    passportNumber: 'MA441002',
    passportIssuePlace: 'Marrakech',
    passportIssueDate: '2018-04-09',
    passportExpiryDate: '2028-04-09',
    expectedDateEntry: '2025-04-22',
    expectedDateLeave: '2025-05-02',
    additionalPurpose: ['Omra'],
    residenceAddressSaudi: 'Makkah Al Azizia',
    hotelName: 'Le Meridien Makkah',
  },

  {
    id: 16,
    personal_picture: '/images/sara.jpg',
    nationality: 'Algérienne',
    firstNameEn: 'Amina',
    fatherNameEn: 'Noureddine',
    lastNameEn: 'Dahmani',
    gender: 'Female',
    maritalStatus: 'Married',
    dateOfBirth: '1990-01-11',
    countryOfBirth: 'Algérie',
    cityOfBirth: 'Constantine',
    profession: 'Biologiste',
    countryResidence: 'France',
    cityResidence: 'Versailles',
    postalCode: '78000',
    address: '5 Avenue Saint Cloud',
    passportType: 'Ordinary',
    passportNumber: 'DZ822110',
    passportIssuePlace: 'Constantine',
    passportIssueDate: '2019-03-16',
    passportExpiryDate: '2029-03-16',
    expectedDateEntry: '2025-06-12',
    expectedDateLeave: '2025-06-22',
    additionalPurpose: ['Tourisme'],
    residenceAddressSaudi: 'Jeddah Al Hamra',
    hotelName: 'Sheraton Jeddah Hotel',
  },

  {
    id: 17,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Marocaine',
    firstNameEn: 'Yassine',
    fatherNameEn: 'Adil',
    lastNameEn: 'Essafi',
    gender: 'Male',
    maritalStatus: 'Single',
    dateOfBirth: '1999-12-07',
    countryOfBirth: 'Maroc',
    cityOfBirth: 'Agadir',
    profession: 'Étudiant',
    countryResidence: 'France',
    cityResidence: 'Montpellier',
    postalCode: '34000',
    address: '24 Rue de l’Université',
    passportType: 'Ordinary',
    passportNumber: 'MA992331',
    passportIssuePlace: 'Agadir',
    passportIssueDate: '2022-01-08',
    passportExpiryDate: '2032-01-08',
    expectedDateEntry: '2025-03-21',
    expectedDateLeave: '2025-03-29',
    additionalPurpose: ['Omra'],
    residenceAddressSaudi: 'Medina North Gate',
    hotelName: 'Al Haram Hotel',
  },

  {
    id: 18,
    personal_picture: '/images/sara.jpg',
    nationality: 'Tunisienne',
    firstNameEn: 'Rania',
    fatherNameEn: 'Lotfi',
    lastNameEn: 'Gharbi',
    gender: 'Female',
    maritalStatus: 'Single',
    dateOfBirth: '1996-05-15',
    countryOfBirth: 'Tunisie',
    cityOfBirth: 'Kairouan',
    profession: 'Développeuse Web',
    countryResidence: 'France',
    cityResidence: 'Reims',
    postalCode: '51100',
    address: '9 Rue du Général Leclerc',
    passportType: 'Ordinary',
    passportNumber: 'TN778820',
    passportIssuePlace: 'Kairouan',
    passportIssueDate: '2020-10-22',
    passportExpiryDate: '2030-10-22',
    expectedDateEntry: '2025-04-16',
    expectedDateLeave: '2025-04-28',
    additionalPurpose: ['Tourisme'],
    residenceAddressSaudi: 'Riyadh Al Malaz',
    hotelName: 'Crowne Plaza Riyadh',
  },

  {
    id: 19,
    personal_picture: '/images/mohamed.jpg',
    nationality: 'Libanaise',
    firstNameEn: 'Hassan',
    fatherNameEn: 'Rami',
    lastNameEn: 'Chami',
    gender: 'Male',
    maritalStatus: 'Married',
    dateOfBirth: '1986-09-02',
    countryOfBirth: 'Liban',
    cityOfBirth: 'Beyrouth',
    profession: 'Entrepreneur',
    countryResidence: 'France',
    cityResidence: 'Dijon',
    postalCode: '21000',
    address: '7 Boulevard Carnot, Dijon',
    passportType: 'Ordinary',
    passportNumber: 'LB221090',
    passportIssuePlace: 'Beirut',
    passportIssueDate: '2021-05-05',
    passportExpiryDate: '2031-05-05',
    expectedDateEntry: '2025-10-17',
    expectedDateLeave: '2025-10-30',
    additionalPurpose: ['Affaires'],
    residenceAddressSaudi: 'Riyadh Al Waha',
    hotelName: 'Four Seasons Riyadh',
  },

  {
    id: 20,
    personal_picture: '/images/sara.jpg',
    nationality: 'Marocaine',
    firstNameEn: 'Houda',
    fatherNameEn: 'Khalid',
    lastNameEn: 'El Idrissi',
    gender: 'Female',
    maritalStatus: 'Married',
    dateOfBirth: '1992-03-23',
    countryOfBirth: 'Maroc',
    cityOfBirth: 'Meknès',
    profession: 'Médecin Généraliste',
    countryResidence: 'France',
    cityResidence: 'Metz',
    postalCode: '57000',
    address: '38 Rue Serpenoise, Metz',
    passportType: 'Ordinary',
    passportNumber: 'MA555890',
    passportIssuePlace: 'Meknès',
    passportIssueDate: '2017-02-10',
    passportExpiryDate: '2027-02-10',
    expectedDateEntry: '2025-05-09',
    expectedDateLeave: '2025-05-21',
    additionalPurpose: ['Omra'],
    residenceAddressSaudi: 'Medina Central',
    hotelName: 'Anwar Al Madinah Mövenpick',
  },
];
